'''
The checked-in protobuf bindings must not demand a newer runtime than the package
declares.

Every ``videoflow/v1/*_pb2.py`` embeds the version of the protoc that generated
it, and the protobuf runtime refuses to load gencode newer than itself
(``VersionError: gencode 7.35.0 runtime 5.29.6``). ``protobuf>=5.27`` in
pyproject.toml is therefore only honest while the bindings were generated by a
5.27 protoc — which is why scripts/gen-proto.sh runs the pinned grpcio-tools.
v1.0.0 shipped bindings regenerated with an unpinned protoc and broke every
image that pinned protobuf < 6; this keeps that from happening again.

Pure/unit: reads the files, imports nothing.
'''
import glob
import os
import re
import tomllib

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_GENCODE = re.compile(r'ValidateProtobufRuntimeVersion\(\s*_runtime_version\.Domain\.PUBLIC,\s*'
                      r'(?P<major>\d+),\s*(?P<minor>\d+),\s*(?P<patch>\d+),', re.MULTILINE)
_FLOOR = re.compile(r'^protobuf>=(?P<major>\d+)\.(?P<minor>\d+)')


def _declared_floor() -> tuple[int, int]:
    with open(os.path.join(ROOT, 'pyproject.toml'), 'rb') as f:
        project = tomllib.load(f)['project']
    requirements = [r for group in project['optional-dependencies'].values() for r in group]
    floors = {m.groups() for r in requirements if (m := _FLOOR.match(r))}
    assert len(floors) == 1, f'the extras disagree on the protobuf floor: {floors}'
    major, minor = floors.pop()
    return int(major), int(minor)


@pytest.mark.parametrize('path', sorted(glob.glob(os.path.join(ROOT, 'videoflow', 'v1', '*_pb2.py'))),
                         ids = os.path.basename)
def test_gencode_version_is_within_the_declared_runtime_floor(path):
    with open(path) as f:
        match = _GENCODE.search(f.read())
    assert match, f'{path} carries no ValidateProtobufRuntimeVersion call'
    gencode = (int(match['major']), int(match['minor']))
    assert gencode <= _declared_floor(), (
        f'{os.path.basename(path)} was generated by protoc {match["major"]}.{match["minor"]}.{match["patch"]}, '
        f'newer than the protobuf>={".".join(map(str, _declared_floor()))} floor pyproject.toml declares — '
        f'regenerate with the pinned grpcio-tools (scripts/gen-proto.sh), or raise the floor on purpose.')
