# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: videoflow/v1/envelope.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'videoflow/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from videoflow.v1 import error_pb2 as videoflow_dot_v1_dot_error__pb2
from videoflow.v1 import value_pb2 as videoflow_dot_v1_dot_value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bvideoflow/v1/envelope.proto\x12\x0cvideoflow.v1\x1a\x18videoflow/v1/error.proto\x1a\x18videoflow/v1/value.proto\"\xca\x03\n\x08\x45nvelope\x12\t\n\x01v\x18\x01 \x01(\r\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.videoflow.v1.MsgType\x12\x15\n\rproducer_name\x18\x03 \x01(\t\x12\x0f\n\x07\x66low_id\x18\x04 \x01(\t\x12\x0e\n\x06run_id\x18\x05 \x01(\t\x12\x10\n\x08trace_id\x18\x06 \x01(\t\x12\x0b\n\x03seq\x18\x07 \x01(\x04\x12\x15\n\x08\x65vent_ts\x18\x08 \x01(\x01H\x00\x88\x01\x01\x12\x0f\n\x07span_id\x18\t \x01(\t\x12\x16\n\x0eparent_span_id\x18\n \x01(\t\x12\x12\n\nreplica_id\x18\x0b \x01(\r\x12\x36\n\x08metadata\x18\x0c \x03(\x0b\x32$.videoflow.v1.Envelope.MetadataEntry\x12\x14\n\x0cpayload_type\x18\r \x01(\t\x12\x0f\n\x07payload\x18\x0e \x01(\x0c\x12\'\n\x05\x65rror\x18\x0f \x01(\x0b\x32\x13.videoflow.v1.ErrorH\x01\x88\x01\x01\x1a\x44\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.videoflow.v1.Value:\x02\x38\x01\x42\x0b\n\t_event_tsB\x08\n\x06_error*\\\n\x07MsgType\x12\x18\n\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rMSG_TYPE_DATA\x10\x01\x12\x10\n\x0cMSG_TYPE_EOS\x10\x02\x12\x12\n\x0eMSG_TYPE_ABORT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoflow.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE_METADATAENTRY']._loaded_options = None
  _globals['_ENVELOPE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MSGTYPE']._serialized_start=558
  _globals['_MSGTYPE']._serialized_end=650
  _globals['_ENVELOPE']._serialized_start=98
  _globals['_ENVELOPE']._serialized_end=556
  _globals['_ENVELOPE_METADATAENTRY']._serialized_start=465
  _globals['_ENVELOPE_METADATAENTRY']._serialized_end=533
# @@protoc_insertion_point(module_scope)
