# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: videoflow/v1/error.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'videoflow/v1/error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18videoflow/v1/error.proto\x12\x0cvideoflow.v1\"\x80\x02\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06remedy\x18\x03 \x01(\t\x12.\n\x0b\x64isposition\x18\x04 \x01(\x0e\x32\x19.videoflow.v1.Disposition\x12\x0c\n\x04node\x18\x05 \x01(\t\x12\x10\n\x08trace_id\x18\x06 \x01(\t\x12\x15\n\rnum_delivered\x18\x07 \x01(\r\x12\x31\n\x07\x63ontext\x18\x08 \x03(\x0b\x32 .videoflow.v1.Error.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*{\n\x0b\x44isposition\x12\x1b\n\x17\x44ISPOSITION_UNSPECIFIED\x10\x00\x12\x16\n\x12\x44ISPOSITION_POISON\x10\x01\x12\x19\n\x15\x44ISPOSITION_TRANSIENT\x10\x02\x12\x1c\n\x18\x44ISPOSITION_WORKER_FATAL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoflow.v1.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERROR_CONTEXTENTRY']._loaded_options = None
  _globals['_ERROR_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_DISPOSITION']._serialized_start=301
  _globals['_DISPOSITION']._serialized_end=424
  _globals['_ERROR']._serialized_start=43
  _globals['_ERROR']._serialized_end=299
  _globals['_ERROR_CONTEXTENTRY']._serialized_start=253
  _globals['_ERROR_CONTEXTENTRY']._serialized_end=299
# @@protoc_insertion_point(module_scope)
