# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: videoflow/v1/payloads.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'videoflow/v1/payloads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bvideoflow/v1/payloads.proto\x12\x0cvideoflow.v1\"4\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"k\n\x05\x46rame\x12$\n\x06pixels\x18\x01 \x01(\x0b\x32\x14.videoflow.v1.Tensor\x12\x14\n\x0cpixel_format\x18\x02 \x01(\t\x12\x17\n\ncapture_ts\x18\x03 \x01(\x01H\x00\x88\x01\x01\x42\r\n\x0b_capture_ts\"F\n\nDetections\x12#\n\x05\x62oxes\x18\x01 \x01(\x0b\x32\x14.videoflow.v1.Tensor\x12\x13\n\x0b\x63lass_names\x18\x02 \x03(\t\".\n\x06Tracks\x12$\n\x06tracks\x18\x01 \x01(\x0b\x32\x14.videoflow.v1.Tensor\"@\n\x07\x42lobRef\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12\x1a\n\x12inner_payload_type\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoflow.v1.payloads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=45
  _globals['_TENSOR']._serialized_end=97
  _globals['_FRAME']._serialized_start=99
  _globals['_FRAME']._serialized_end=206
  _globals['_DETECTIONS']._serialized_start=208
  _globals['_DETECTIONS']._serialized_end=278
  _globals['_TRACKS']._serialized_start=280
  _globals['_TRACKS']._serialized_end=326
  _globals['_BLOBREF']._serialized_start=328
  _globals['_BLOBREF']._serialized_end=392
# @@protoc_insertion_point(module_scope)
