'''
Processors that use the TwelveLabs video-understanding platform.

This module provides ``PegasusAnalyzer``, a processor node that sends a
whole video (referenced by a publicly accessible URL or by a TwelveLabs
asset id) to the TwelveLabs Pegasus model and returns the generated text
analysis.

Pegasus reasons over an entire clip rather than over a single frame, so
this node is meant to sit downstream of a producer/processor that emits a
video reference (a URL or asset id string), not the per-frame ``np.array``
stream consumed by the detectors and trackers in this package.

Requires the official ``twelvelabs`` SDK (``pip install twelvelabs``) and a
TwelveLabs API key. You can grab a free API key at https://twelvelabs.io.
'''
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

import os

from ...core.node import OneTaskProcessorNode

PEGASUS_DEFAULT_MODEL = 'pegasus1.5'


class PegasusAnalyzer(OneTaskProcessorNode):
    '''
    Analyzes a video with the TwelveLabs Pegasus model and returns the
    generated text.

    The node receives a video reference as input and runs a prompt-based
    analysis against it server-side, returning the text Pegasus produces.
    The video reference is interpreted according to ``input_type``:

    - ``'url'`` (default): a publicly accessible video URL.
    - ``'asset_id'``: the id of an asset already uploaded to TwelveLabs.

    Because the node holds an API client and is network bound, it derives
    from ``OneTaskProcessorNode`` (a single task instance).

    - Arguments:
        - prompt (str): the instruction sent to Pegasus, e.g. \
            ``"Summarize this video"``.
        - api_key (str): TwelveLabs API key. If ``None`` (default), it is \
            read from the ``TWELVELABS_API_KEY`` environment variable.
        - model_name (str): Pegasus model to use. Defaults to \
            ``'pegasus1.5'``.
        - max_tokens (int): maximum number of tokens to generate. \
            Defaults to 2048.
        - temperature (float): sampling temperature. If ``None`` (default), \
            the server default is used.
        - input_type (str): how to interpret the input video reference, \
            either ``'url'`` or ``'asset_id'``. Defaults to ``'url'``.

    - Raises:
        - ``ImportError`` if the ``twelvelabs`` SDK is not installed (raised \
            lazily in ``open``).
        - ``ValueError`` if no API key is provided and \
            ``TWELVELABS_API_KEY`` is not set, or if ``input_type`` is not \
            one of ``'url'`` / ``'asset_id'``.
    '''
    def __init__(self, prompt, api_key = None, model_name = PEGASUS_DEFAULT_MODEL,
                 max_tokens = 2048, temperature = None, input_type = 'url',
                 *args, **kwargs):
        if input_type not in ('url', 'asset_id'):
            raise ValueError("input_type must be 'url' or 'asset_id', got {}".format(input_type))
        self._prompt = prompt
        self._api_key = api_key
        self._model_name = model_name
        self._max_tokens = max_tokens
        self._temperature = temperature
        self._input_type = input_type
        self._client = None
        super(PegasusAnalyzer, self).__init__(*args, **kwargs)

    def open(self):
        '''
        Creates the TwelveLabs client. Resolves the API key from the
        ``api_key`` argument or the ``TWELVELABS_API_KEY`` environment
        variable.
        '''
        try:
            from twelvelabs import TwelveLabs
        except ImportError:
            raise ImportError('The twelvelabs SDK is required to use PegasusAnalyzer. '
                              'Install it with `pip install twelvelabs`.')
        api_key = self._api_key or os.environ.get('TWELVELABS_API_KEY')
        if not api_key:
            raise ValueError('No TwelveLabs API key provided. Pass api_key or set '
                             'the TWELVELABS_API_KEY environment variable.')
        self._client = TwelveLabs(api_key = api_key)

    def close(self):
        '''
        Releases the client reference.
        '''
        self._client = None

    def _video_context(self, video_ref):
        if self._input_type == 'url':
            from twelvelabs.types.video_context import VideoContext_Url
            return VideoContext_Url(url = video_ref)
        from twelvelabs.types.video_context import VideoContext_AssetId
        return VideoContext_AssetId(asset_id = video_ref)

    def process(self, video_ref : str) -> str:
        '''
        Sends ``video_ref`` to Pegasus and returns the generated text.

        - Arguments:
            - video_ref (str): a video URL or a TwelveLabs asset id, \
                according to ``input_type``.

        - Returns:
            - The text generated by Pegasus (the ``data`` field of the \
                analyze response).

        - Raises:
            - ``RuntimeError`` if called before ``open`` (no client).
        '''
        if self._client is None:
            self.open()
        kwargs = dict(
            model_name = self._model_name,
            video = self._video_context(video_ref),
            prompt = self._prompt,
            max_tokens = self._max_tokens,
        )
        if self._temperature is not None:
            kwargs['temperature'] = self._temperature
        response = self._client.analyze(**kwargs)
        return response.data
